title: Zea
description: >-
  Personal website, including computer science notes, programming, hacking,
  philosophy, C, Lisp, Assembly and several other things that could also help
  you learn new things.
tags:
  - programming
  - cyber security
  - computer science
  - free
  - courses
  - learning
  - deep learning
  - C
  - assembly
  - lisp
  - perl
  - personal site
  - free software

highlighter: rouge

url: "https://zeabanger.gq"
plugins:
  - jekyll-sitemap