title: Zea
description: >-
  A place where I store my notes about computer science, programming, hacking
  and amongst other things.
tags:
  - programming
  - cyber security
  - computer science
  - free
  - courses
  - learning